export type ItemRarity = 'common' | 'epic' | 'legendary'

export type ProfileItem = {
  id: string
  name: string
  rarity: ItemRarity
  category: string
  description: string
  iconSrc: string
}

export const profileItems: readonly ProfileItem[] = [
  {
    id: 'club-toaster',
    name: 'Клубный тостер',
    rarity: 'common',
    category: 'Хлеб и выпечка',
    description: 'Любит хрустящие завтраки и аромат свежей булочной.',
    iconSrc: '/assets/items/club-toaster.webp',
  },
  {
    id: 'milk-pitcher',
    name: 'Молочный кувшин',
    rarity: 'common',
    category: 'Молочные продукты',
    description: 'Знает, что делает утро нежнее, а дверцу холодильника — привычнее.',
    iconSrc: '/assets/items/milk-pitcher.webp',
  },
  {
    id: 'fruit-basket',
    name: 'Фруктовая корзинка',
    rarity: 'common',
    category: 'Фрукты',
    description: 'Подсказывает заглянуть туда, где всегда ярко, сочно и по сезону.',
    iconSrc: '/assets/items/fruit-basket.webp',
  },
  {
    id: 'vegetable-crate',
    name: 'Овощной ящик',
    rarity: 'common',
    category: 'Овощи и зелень',
    description: 'Собирает всё хрустящее, зелёное и будто только что с грядки.',
    iconSrc: '/assets/items/vegetable-crate.webp',
  },
  {
    id: 'travel-mug',
    name: 'Термокружка',
    rarity: 'common',
    category: 'Кофе и чай',
    description: 'Тянется к полкам, которые бодрят утром и согревают вечером.',
    iconSrc: '/assets/items/travel-mug.webp',
  },
  {
    id: 'snack-bowl',
    name: 'Миска для снеков',
    rarity: 'common',
    category: 'Снеки и орехи',
    description: 'Знает, чем занять руки во время фильма или встречи с друзьями.',
    iconSrc: '/assets/items/snack-bowl.webp',
  },
  {
    id: 'breakfast-pan',
    name: 'Сковорода завтрака',
    rarity: 'common',
    category: 'Яйца и завтраки',
    description: 'Просыпается раньше всех и собирает быстрый сытный старт дня.',
    iconSrc: '/assets/items/breakfast-pan.webp',
  },
  {
    id: 'baker-apron',
    name: 'Фартук пекаря',
    rarity: 'common',
    category: 'Всё для выпечки',
    description: 'Ищет всё, что превращает домашнюю кухню в маленькую пекарню.',
    iconSrc: '/assets/items/baker-apron.webp',
  },
  {
    id: 'chef-knife',
    name: 'Нож шефа',
    rarity: 'epic',
    category: 'Свежие продукты',
    description: 'Выбирает то, что лучше нарезать и приготовить сегодня, не откладывая.',
    iconSrc: '/assets/items/chef-knife.webp',
  },
  {
    id: 'freezer-chest',
    name: 'Морозильная камера',
    rarity: 'epic',
    category: 'Замороженные продукты',
    description: 'Предпочитает запасы, которым не страшно долгое ожидание.',
    iconSrc: '/assets/items/freezer-chest.webp',
  },
  {
    id: 'power-blender',
    name: 'Блендер здоровья',
    rarity: 'epic',
    category: 'Полезные напитки',
    description: 'Любит яркие смеси, свежий вкус и заряд бодрости в стакане.',
    iconSrc: '/assets/items/power-blender.webp',
  },
  {
    id: 'master-grill',
    name: 'Гриль мастера',
    rarity: 'epic',
    category: 'Мясо и колбасы',
    description: 'Идёт туда, где продукту особенно идут огонь, корочка и дымок.',
    iconSrc: '/assets/items/master-grill.webp',
  },
  {
    id: 'sushi-kit',
    name: 'Набор сушиста',
    rarity: 'epic',
    category: 'Рыба и азиатская кухня',
    description: 'Собирает ингредиенты для ужина с палочками и соевым соусом.',
    iconSrc: '/assets/items/sushi-kit.webp',
  },
  {
    id: 'barista-machine',
    name: 'Кофемашина бариста',
    rarity: 'epic',
    category: 'Кофе и десерты',
    description: 'Понимает идеальную пару для ароматной чашки и маленькой сладкой паузы.',
    iconSrc: '/assets/items/barista-machine.webp',
  },
  {
    id: 'pizza-oven',
    name: 'Печь пиццайоло',
    rarity: 'epic',
    category: 'Пицца и готовая еда',
    description: 'Спасает, когда хочется горячего ужина без долгой готовки.',
    iconSrc: '/assets/items/pizza-oven.webp',
  },
  {
    id: 'picnic-cooler',
    name: 'Холодильник для пикника',
    rarity: 'epic',
    category: 'Холодные напитки и мороженое',
    description: 'Берёт всё, что приятно открыть холодным на прогулке или в жаркий день.',
    iconSrc: '/assets/items/picnic-cooler.webp',
  },
  {
    id: 'golden-chef-hat',
    name: 'Золотой колпак повара',
    rarity: 'legendary',
    category: 'Готовая еда',
    description: 'Знает короткий путь к полноценному обеду, когда готовить совсем некогда.',
    iconSrc: '/assets/items/golden-chef-hat.webp',
  },
  {
    id: 'magic-fridge',
    name: 'Волшебный холодильник',
    rarity: 'legendary',
    category: 'Любимые покупки',
    description: 'Запоминает то, за чем вы возвращаетесь снова и снова.',
    iconSrc: '/assets/items/magic-fridge.webp',
  },
  {
    id: 'royal-cauldron',
    name: 'Королевский казан',
    rarity: 'legendary',
    category: 'Крупы, супы и соусы',
    description: 'Собирает основу для тёплого домашнего блюда в одной большой кастрюле.',
    iconSrc: '/assets/items/royal-cauldron.webp',
  },
  {
    id: 'dragon-wok',
    name: 'Драконий вок',
    rarity: 'legendary',
    category: 'Лапша и азиатская кухня',
    description: 'Любит острое, пряное и то, что удобнее есть палочками.',
    iconSrc: '/assets/items/dragon-wok.webp',
  },
  {
    id: 'crystal-icecream-maker',
    name: 'Кристальная мороженица',
    rarity: 'legendary',
    category: 'Мороженое и десерты',
    description: 'Ищет самый холодный способ сделать обычный день слаще.',
    iconSrc: '/assets/items/crystal-icecream-maker.webp',
  },
  {
    id: 'legendary-sandwich-press',
    name: 'Пресс идеального сэндвича',
    rarity: 'legendary',
    category: 'Хлеб, сыр и колбасы',
    description: 'Соединяет хрустящую основу, нежную середину и сытную начинку.',
    iconSrc: '/assets/items/legendary-sandwich-press.webp',
  },
  {
    id: 'treasure-pantry',
    name: 'Сундук запасов',
    rarity: 'legendary',
    category: 'Бакалея и консервы',
    description: 'Ценит то, что всегда выручает и долго ждёт своего часа.',
    iconSrc: '/assets/items/treasure-pantry.webp',
  },
  {
    id: 'freshness-dome',
    name: 'Купол свежести',
    rarity: 'legendary',
    category: 'Овощи, фрукты и зелень',
    description: 'Тянется к самым ярким цветам и хрусту прямо с грядки.',
    iconSrc: '/assets/items/freshness-dome.webp',
  },
]
