export type ItemRarity = 'common' | 'epic' | 'legendary'

export type ProfileItem = {
  id: string
  name: string
  rarity: ItemRarity
  category: string
  description: string
  iconSrc: string
}

export const profileItems: readonly ProfileItem[] = [
  {
    id: 'club-toaster',
    name: 'Клубный тостер',
    rarity: 'common',
    category: 'Хлеб и выпечка',
    description: 'Усиливает скидки на хлеб, булочки и готовую выпечку.',
    iconSrc: '/assets/items/club-toaster.webp',
  },
  {
    id: 'milk-pitcher',
    name: 'Молочный кувшин',
    rarity: 'common',
    category: 'Молочные продукты',
    description: 'Помогает собрать скидку на молоко, йогурты и творог.',
    iconSrc: '/assets/items/milk-pitcher.webp',
  },
  {
    id: 'fruit-basket',
    name: 'Фруктовая корзинка',
    rarity: 'common',
    category: 'Фрукты',
    description: 'Переносит фокус скидки на свежие фрукты и ягоды.',
    iconSrc: '/assets/items/fruit-basket.webp',
  },
  {
    id: 'vegetable-crate',
    name: 'Овощной ящик',
    rarity: 'common',
    category: 'Овощи и зелень',
    description: 'Усиливает предложения на овощи, салаты и зелень.',
    iconSrc: '/assets/items/vegetable-crate.webp',
  },
  {
    id: 'travel-mug',
    name: 'Термокружка',
    rarity: 'common',
    category: 'Кофе и чай',
    description: 'Настраивает скидку на кофе, чай и горячие напитки.',
    iconSrc: '/assets/items/travel-mug.webp',
  },
  {
    id: 'snack-bowl',
    name: 'Миска для снеков',
    rarity: 'common',
    category: 'Снеки и орехи',
    description: 'Добавляет вес снекам, орехам и быстрым перекусам.',
    iconSrc: '/assets/items/snack-bowl.webp',
  },
  {
    id: 'breakfast-pan',
    name: 'Сковорода завтрака',
    rarity: 'common',
    category: 'Яйца и завтраки',
    description: 'Фокусирует скидку на яйцах и продуктах для завтрака.',
    iconSrc: '/assets/items/breakfast-pan.webp',
  },
  {
    id: 'baker-apron',
    name: 'Фартук пекаря',
    rarity: 'common',
    category: 'Всё для выпечки',
    description: 'Усиливает муку, сахар и другие товары для выпечки.',
    iconSrc: '/assets/items/baker-apron.webp',
  },
  {
    id: 'chef-knife',
    name: 'Нож шефа',
    rarity: 'epic',
    category: 'Свежие продукты',
    description: 'Помогает получить скидку на мясо, рыбу и овощи.',
    iconSrc: '/assets/items/chef-knife.webp',
  },
  {
    id: 'freezer-chest',
    name: 'Морозильная камера',
    rarity: 'epic',
    category: 'Замороженные продукты',
    description: 'Усиливает скидки на заморозку и полуфабрикаты.',
    iconSrc: '/assets/items/freezer-chest.webp',
  },
  {
    id: 'power-blender',
    name: 'Блендер здоровья',
    rarity: 'epic',
    category: 'Полезные напитки',
    description: 'Фокусируется на фруктах, соках и полезных напитках.',
    iconSrc: '/assets/items/power-blender.webp',
  },
  {
    id: 'master-grill',
    name: 'Гриль мастера',
    rarity: 'epic',
    category: 'Мясо и колбасы',
    description: 'Повышает шанс выгодного предложения на мясо и колбасы.',
    iconSrc: '/assets/items/master-grill.webp',
  },
  {
    id: 'sushi-kit',
    name: 'Набор сушиста',
    rarity: 'epic',
    category: 'Рыба и азиатская кухня',
    description: 'Настраивает скидку на рыбу, рис и азиатские продукты.',
    iconSrc: '/assets/items/sushi-kit.webp',
  },
  {
    id: 'barista-machine',
    name: 'Кофемашина бариста',
    rarity: 'epic',
    category: 'Кофе и десерты',
    description: 'Сочетает предложения на кофе, сладости и десерты.',
    iconSrc: '/assets/items/barista-machine.webp',
  },
  {
    id: 'pizza-oven',
    name: 'Печь пиццайоло',
    rarity: 'epic',
    category: 'Пицца и готовая еда',
    description: 'Усиливает скидки на пиццу и блюда, которые нужно разогреть.',
    iconSrc: '/assets/items/pizza-oven.webp',
  },
  {
    id: 'picnic-cooler',
    name: 'Холодильник для пикника',
    rarity: 'epic',
    category: 'Холодные напитки и мороженое',
    description: 'Фокусирует скидку на напитках, льде и мороженом.',
    iconSrc: '/assets/items/picnic-cooler.webp',
  },
  {
    id: 'golden-chef-hat',
    name: 'Золотой колпак повара',
    rarity: 'legendary',
    category: 'Готовая еда',
    description: 'Создаёт сильную скидку на готовые блюда и кулинарию.',
    iconSrc: '/assets/items/golden-chef-hat.webp',
  },
  {
    id: 'magic-fridge',
    name: 'Волшебный холодильник',
    rarity: 'legendary',
    category: 'Любимые покупки',
    description: 'Собирает скидку вокруг любимых и повторных покупок.',
    iconSrc: '/assets/items/magic-fridge.webp',
  },
  {
    id: 'royal-cauldron',
    name: 'Королевский казан',
    rarity: 'legendary',
    category: 'Крупы, супы и соусы',
    description: 'Объединяет выгоду на крупы, ингредиенты для супов и соусы.',
    iconSrc: '/assets/items/royal-cauldron.webp',
  },
  {
    id: 'dragon-wok',
    name: 'Драконий вок',
    rarity: 'legendary',
    category: 'Лапша и азиатская кухня',
    description: 'Усиливает лапшу, соусы и продукты азиатской кухни.',
    iconSrc: '/assets/items/dragon-wok.webp',
  },
  {
    id: 'crystal-icecream-maker',
    name: 'Кристальная мороженица',
    rarity: 'legendary',
    category: 'Мороженое и десерты',
    description: 'Создаёт выгодную подборку мороженого и десертов.',
    iconSrc: '/assets/items/crystal-icecream-maker.webp',
  },
  {
    id: 'legendary-sandwich-press',
    name: 'Пресс идеального сэндвича',
    rarity: 'legendary',
    category: 'Хлеб, сыр и колбасы',
    description: 'Связывает в одной скидке ингредиенты для сэндвичей.',
    iconSrc: '/assets/items/legendary-sandwich-press.webp',
  },
  {
    id: 'treasure-pantry',
    name: 'Сундук запасов',
    rarity: 'legendary',
    category: 'Бакалея и консервы',
    description: 'Фокусирует скидку на долгом хранении и домашних запасах.',
    iconSrc: '/assets/items/treasure-pantry.webp',
  },
  {
    id: 'freshness-dome',
    name: 'Купол свежести',
    rarity: 'legendary',
    category: 'Овощи, фрукты и зелень',
    description: 'Создаёт сильную скидку на весь свежий растительный набор.',
    iconSrc: '/assets/items/freshness-dome.webp',
  },
]
