export type ItemRarity = 'common' | 'epic' | 'legendary'

export type ProfileItem = {
  id: string
  name: string
  rarity: ItemRarity
  category: string
  description: string
  iconSrc: string
}

export const profileItems: readonly ProfileItem[] = [
  {
    id: 'club-toaster',
    name: 'Clubhouse Toaster',
    rarity: 'common',
    category: 'Bread & Bakery',
    description: 'Loves crunchy breakfasts and the smell of a fresh bakery.',
    iconSrc: '/assets/items/club-toaster.webp',
  },
  {
    id: 'milk-pitcher',
    name: 'Milk Pitcher',
    rarity: 'common',
    category: 'Dairy',
    description: 'Knows what makes a morning softer and a fridge door more familiar.',
    iconSrc: '/assets/items/milk-pitcher.webp',
  },
  {
    id: 'fruit-basket',
    name: 'Fruit Basket',
    rarity: 'common',
    category: 'Fruit',
    description: 'Points you to the shelf that is always bright, juicy and in season.',
    iconSrc: '/assets/items/fruit-basket.webp',
  },
  {
    id: 'vegetable-crate',
    name: 'Vegetable Crate',
    rarity: 'common',
    category: 'Vegetables & Herbs',
    description: 'Collects everything crisp, green and freshly picked.',
    iconSrc: '/assets/items/vegetable-crate.webp',
  },
  {
    id: 'travel-mug',
    name: 'Travel Mug',
    rarity: 'common',
    category: 'Coffee & Tea',
    description: 'Reaches for the shelves that wake you up and warm the evening.',
    iconSrc: '/assets/items/travel-mug.webp',
  },
  {
    id: 'snack-bowl',
    name: 'Snack Bowl',
    rarity: 'common',
    category: 'Snacks & Nuts',
    description: 'Knows what keeps your hands busy during a film or a night with friends.',
    iconSrc: '/assets/items/snack-bowl.webp',
  },
  {
    id: 'breakfast-pan',
    name: 'Breakfast Pan',
    rarity: 'common',
    category: 'Eggs & Breakfast',
    description: 'Wakes up before everyone else and puts together a quick, filling start.',
    iconSrc: '/assets/items/breakfast-pan.webp',
  },
  {
    id: 'baker-apron',
    name: "Baker's Apron",
    rarity: 'common',
    category: 'Baking Supplies',
    description: 'Looks for anything that turns a home kitchen into a small bakery.',
    iconSrc: '/assets/items/baker-apron.webp',
  },
  {
    id: 'chef-knife',
    name: "Chef's Knife",
    rarity: 'epic',
    category: 'Fresh Food',
    description: 'Picks what is best sliced and cooked today rather than later.',
    iconSrc: '/assets/items/chef-knife.webp',
  },
  {
    id: 'freezer-chest',
    name: 'Freezer Chest',
    rarity: 'epic',
    category: 'Frozen Food',
    description: 'Prefers supplies that do not mind a long wait.',
    iconSrc: '/assets/items/freezer-chest.webp',
  },
  {
    id: 'power-blender',
    name: 'Power Blender',
    rarity: 'epic',
    category: 'Healthy Drinks',
    description: 'Loves bright blends, fresh taste and a glass full of energy.',
    iconSrc: '/assets/items/power-blender.webp',
  },
  {
    id: 'master-grill',
    name: "Master's Grill",
    rarity: 'epic',
    category: 'Meat & Sausages',
    description: 'Goes where fire, crust and a little smoke suit the food best.',
    iconSrc: '/assets/items/master-grill.webp',
  },
  {
    id: 'sushi-kit',
    name: 'Sushi Kit',
    rarity: 'epic',
    category: 'Fish & Asian Cuisine',
    description: 'Gathers the ingredients for a dinner with chopsticks and soy sauce.',
    iconSrc: '/assets/items/sushi-kit.webp',
  },
  {
    id: 'barista-machine',
    name: 'Barista Machine',
    rarity: 'epic',
    category: 'Coffee & Desserts',
    description: 'Understands the perfect pair: a fragrant cup and a small sweet pause.',
    iconSrc: '/assets/items/barista-machine.webp',
  },
  {
    id: 'pizza-oven',
    name: 'Pizzaiolo Oven',
    rarity: 'epic',
    category: 'Pizza & Ready Meals',
    description: 'Saves the evening when you want a hot dinner without the cooking.',
    iconSrc: '/assets/items/pizza-oven.webp',
  },
  {
    id: 'picnic-cooler',
    name: 'Picnic Cooler',
    rarity: 'epic',
    category: 'Cold Drinks & Ice Cream',
    description: 'Takes everything worth opening cold on a walk or on a hot day.',
    iconSrc: '/assets/items/picnic-cooler.webp',
  },
  {
    id: 'golden-chef-hat',
    name: "Golden Chef's Hat",
    rarity: 'legendary',
    category: 'Ready Meals',
    description: 'Knows the short way to a full lunch when there is no time to cook.',
    iconSrc: '/assets/items/golden-chef-hat.webp',
  },
  {
    id: 'magic-fridge',
    name: 'Magic Fridge',
    rarity: 'legendary',
    category: 'Favourite Buys',
    description: 'Remembers what you come back for again and again.',
    iconSrc: '/assets/items/magic-fridge.webp',
  },
  {
    id: 'royal-cauldron',
    name: 'Royal Cauldron',
    rarity: 'legendary',
    category: 'Grains, Soups & Sauces',
    description: 'Gathers the base of a warm home-cooked dish in one big pot.',
    iconSrc: '/assets/items/royal-cauldron.webp',
  },
  {
    id: 'dragon-wok',
    name: 'Dragon Wok',
    rarity: 'legendary',
    category: 'Noodles & Asian Cuisine',
    description: 'Loves spicy, fragrant food that is easier to eat with chopsticks.',
    iconSrc: '/assets/items/dragon-wok.webp',
  },
  {
    id: 'crystal-icecream-maker',
    name: 'Crystal Ice Cream Maker',
    rarity: 'legendary',
    category: 'Ice Cream & Desserts',
    description: 'Looks for the coldest way to make an ordinary day sweeter.',
    iconSrc: '/assets/items/crystal-icecream-maker.webp',
  },
  {
    id: 'legendary-sandwich-press',
    name: 'Perfect Sandwich Press',
    rarity: 'legendary',
    category: 'Bread, Cheese & Deli',
    description: 'Brings together a crisp base, a soft middle and a filling worth the bite.',
    iconSrc: '/assets/items/legendary-sandwich-press.webp',
  },
  {
    id: 'treasure-pantry',
    name: 'Pantry Chest',
    rarity: 'legendary',
    category: 'Groceries & Canned Food',
    description: 'Values what always helps out and waits patiently for its turn.',
    iconSrc: '/assets/items/treasure-pantry.webp',
  },
  {
    id: 'freshness-dome',
    name: 'Freshness Dome',
    rarity: 'legendary',
    category: 'Vegetables, Fruit & Herbs',
    description: 'Reaches for the brightest colours and the crunch straight from the field.',
    iconSrc: '/assets/items/freshness-dome.webp',
  },
]
